### ISSUE TITLE
Documentação do projeto de interface e do fluxo de telas do sistema de uma aplicação web

### ISSUE THREAD

**Issue by tiagodlobo** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e4-proj-infra-t1-pmv-ads-2023-2-e4-projmoodtracker#11]

**Comment by EduardoLIdeAndrade** [comment]
https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e4-proj-infra-t1-pmv-ads-2023-2-e4-projmoodtracker/blob/main/docs/img/Mapafluxo%201.2.jpeg

**Comment by EduardoLIdeAndrade** [comment]
Fluxo de ida e volta para do cliente.
